%\VignetteIndexEntry{crlmm copy number Vignette for Illumina}
%\VignetteDepends{crlmm}
%\VignetteKeywords{crlmm, illumina}
%\VignettePackage{crlmm}
\documentclass{article}
\usepackage{graphicx}
\usepackage{natbib}
\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}
\newcommand{\Rcode}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textsf{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}
\newcommand{\oligo}{\Rpackage{oligo }}
\newcommand{\R}{\textsf{R}}

\begin{document}
\title{Copy number estimation and genotype calling with \Rpackage{crlmm}}
\date{Oct, 2009}
\author{Rob Scharpf}
\maketitle

<<setup, echo=FALSE, results=hide>>=
options(width=60)
options(continue=" ")
options(prompt="R> ")
@ 

<<crlmm>>=
library(crlmm)
crlmm:::validCdfNames()
outdir <- "/thumper/ctsa/snpmicroarray/rs/data/hapmap/illumina/HumanCNV370-Duo"
datadir <- "/thumper/ctsa/snpmicroarray/illumina/IDATS/370k"
cdfName <- "human370v1c"
@ 

<<samplesToProcess>>=
samplesheet = read.csv(file.path(datadir, "HumanHap370Duo_Sample_Map.csv"), header=TRUE, as.is=TRUE)
## Excluding a few of the problem samples
samplesheet <- samplesheet[-c(28:46,61:75,78:79), ]
arrayNames <- file.path(datadir, unique(samplesheet[, "SentrixPosition"]))
##Check that files exist
grnfiles = all(file.exists(paste(arrayNames, ".Grn.dat", sep="")))
redfiles = all(file.exists(paste(arrayNames, ".Red.dat", sep="")))
@ 

Alternatively, arguments to the readIdatFiles can be passed through the
{\tt ...} argument of the \R{} function \Robject{crlmmWrapper}.

<<wrapper>>=
crlmmWrapper(sampleSheet=samplesheet,
	     arrayNames=arrayNames,
	     arrayInfoColNames=list(barcode=NULL, position="SentrixPosition"), 
	     saveDate=TRUE,
	     cdfName=cdfName,
	     load.it=TRUE,
	     save.it=TRUE,
	     intensityFile=file.path(outdir, "normalizedIntensities.rda"),
	     crlmmFile=file.path(outdir, "snpsetObject.rda"),
	     rgFile=file.path(outdir, "rgFile.rda"))
@ 

This creates a \Robject{crlmmSetList} object in the \Robject{outdir}
directory.  The first element of this object contains the
quantile-normalized A and B intensities.  The second element in the list
contains the crlmm genotype calls.  


<<SNR>>=
CHR <- 1
filename <- paste(outdir, "/crlmmSetList_", CHR, ".rda", sep="")
load(filename)
hist(crlmmSetList[[1]]$SNR)
@ 

Run update on the CrlmmSetList object to obtain copy number estimates. Estimate
copy number for chromosome 1.

<<estimateCn>>=
update(filename)
##Or equivalently,
##crlmmSetList <- computeCopynumber(crlmmSetList)
##save(crlmmSetList, file=file.path(outdir, paste("crlmmSetList_", CHR, ".rda", sep="")))
@ 

Samples with low signal to noise ratios tend to have a lot of variation
in the point estimates of copy number.  One may want to exclude these
samples, or smooth after filtering outliers.  Here we load the
crlmmSetList object.  See the copynumber.Rnw vignette for example plots.

<<crlmmSetList>>=
##reload the updated object
load(filename)
cn <- copyNumber(crlmmSetList)
@ 

\section{Session information}
<<sessionInfo, results=tex>>=
toLatex(sessionInfo())
@ 


\end{document}



