setGeneric("A<-", function(object, value) standardGeneric("A<-"))
setGeneric("B<-", function(object, value) standardGeneric("B<-"))

setGeneric("getParam", function(object, name, ...) standardGeneric("getParam"))
setGeneric("cnIndex", function(object) standardGeneric("cnIndex"))
setGeneric("cnNames", function(object) standardGeneric("cnNames"))
setGeneric("confs", function(object) standardGeneric("confs"))
setGeneric("computeCopynumber", function(object) standardGeneric("computeCopynumber"))
setGeneric("crlmm", function(object, ...) standardGeneric("crlmm"))
setGeneric("crlmmOptions", function(object) standardGeneric("crlmmOptions"))
setGeneric("crlmmOptions<-", function(object, value) standardGeneric("crlmmOptions<-"))
setGeneric("construct", function(object, filenames) standardGeneric("construct"))

setGeneric("getOptions", function(object) standardGeneric("getOptions"))

##setGeneric("getA", function(object) standardGeneric("getA"))
##setGeneric("getB", function(object) standardGeneric("getB"))
##setGeneric("getG", function(object) standardGeneric("getG"))
##setGeneric("getR", function(object) standardGeneric("getR"))
##setGeneric("getZero", function(object) standardGeneric("getZero"))
##setGeneric("getCalls", function(object) standardGeneric("getCalls"))
##setGeneric("getConfs", function(object) standardGeneric("getConfs"))
##setGeneric("getCA", function(object) standardGeneric("getCA"))
##setGeneric("getCB", function(object) standardGeneric("getCB"))
setGeneric("getPhenoData", function(object) standardGeneric("getPhenoData"))
setGeneric("getFeatureData", function(object) standardGeneric("getFeatureData"))
setGeneric("getProtocolData", function(object, filenames) standardGeneric("getProtocolData"))
setGeneric("getGenomeAnnotation", function(object, ...) standardGeneric("getGenomeAnnotation"))
setGeneric("getLinearModelParam", function(object, ...) standardGeneric("getLinearModelParam"))

##setGeneric("initializeStorage", function(object) standardGeneric("initializeStorage")) 
setGeneric("prediction", function(x, ...) standardGeneric("prediction")) 
setGeneric("genomeAnnotation", function(object) standardGeneric("genomeAnnotation"))
setGeneric("genomeAnnotation<-", function(object,value) standardGeneric("genomeAnnotation<-"))
setGeneric("lM", function(object) standardGeneric("lM"))
setGeneric("lM<-", function(object, value) standardGeneric("lM<-"))

##setGeneric("nFeatures", function(object) standardGeneric("nFeatures"))

setGeneric("pr", function(object, name, batch, value) standardGeneric("pr"))
setGeneric("rma", function(object) standardGeneric("rma"))
setGeneric("snprma", function(object, ...) standardGeneric("snprma")) 
setGeneric("snpIndex", function(object) standardGeneric("snpIndex"))
setGeneric("snpNames", function(object) standardGeneric("snpNames"))
##setGeneric("splitByChromosome", function(object, ...) standardGeneric("splitByChromosome"))

setGeneric("R", function(object) standardGeneric("R"))
setGeneric("G", function(object) standardGeneric("G"))
setGeneric("Z", function(object) standardGeneric("Z"))
setGeneric("X", function(object) standardGeneric("X"))
setGeneric("Y", function(object) standardGeneric("Y"))
setMethod("R", "IlluminaRGSet", function(object) assayDataElement(object, "R"))
setMethod("G", "IlluminaRGSet", function(object) assayDataElement(object, "G"))
setMethod("Z", "IlluminaRGSet", function(object) assayDataElement(object, "zero"))
setMethod("X", "IlluminaXYSet", function(object) assayDataElement(object, "X"))
setMethod("Y", "IlluminaXYSet", function(object) assayDataElement(object, "Y"))
setMethod("Z", "IlluminaXYSet", function(object) assayDataElement(object, "zero"))
