stupidSplineBasis <- function(x,knots){
  x <- pmin(x,knots[3])
  x <- pmax(x,knots[1])
  cbind(1, x, x^2, pmax(0, (x-knots[2]))^2)
}

changeToCrlmmAnnotationName <- function(x){
  pkgDir <- system.file(package=THISPKG)
  wanted <- paste(tolower(gsub("_", "", x)), "crlmm.stuff", sep=".")
  file.path(pkgDir, "extdata", wanted)
}

getCrlmmAnnotationName <- function(x){
  paste(tolower(gsub("_", "", x)), "Crlmm", sep="")
}

medianSummaries <- function(mat, grps)
  .Call("R_subColSummarize_median", mat, grps, PACKAGE = "preprocessCore")

intMedianSummaries <- function(mat, grps)
  as.integer(medianSummaries(mat, grps))

testProb <- function(p)
  .Call("test", p)


list.celfiles <-   function(...){
  files <- list.files(...)
  return(files[grep("\\.[cC][eE][lL]$", files)])
}

## .crlmmPkgEnv is an enviroment that will
## store all the variables used by the pkg.
## it's meant to not overwrite user's variables
## and get rid of the NOTES generated by
## R CMD check

isLoaded <- function(dataset, environ=.crlmmPkgEnv)
  exists(dataset, envir=environ)

getVarInEnv <- function(dataset, environ=.crlmmPkgEnv){
  if (!isLoaded(dataset))
    stop("Variable ", dataset, " not found in .crlmmPkgEnv")
  environ[[dataset]]
}
